spring.application.name=associacao
server.port=8080
spring.datasource.url=jdbc:mariadb://localhost/associacao
spring.datasource.username=root
spring.datasource.password=135790
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver